FROM jenkins/jenkins:latest

USER root

RUN sudo apt-get update

RUN sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN sudo apt-get update

RUN sudo apt-get install -y docker-ce docker-ce-cli containerd.io

RUN systemctl enable docker

RUN systemctl start docker

RUN usermod -aG docker compadmin

ENTRYPOINT ["/usr/bin/tini" "--" "/usr/local/bin/jenkins.sh"]% 
